#cloud-config
ssh_pwauth: true

chpasswd:
  list: |
    root:${root_hashed_password}
  expire: false

users:
  - name: root
    lock_passwd: false
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_public_key}

  - name: ansible
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: true
    ssh_authorized_keys:
      - ${ssh_public_key}

packages:
  - qemu-guest-agent
  - curl
  - vim

runcmd:
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent

  - sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config

  - sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config

  - systemctl restart sshd
